---
title: "SAL Project 1"
author: "Annie Glenning"
date: "2024-10-14"
output: html_document
---

```{r}
# downloading the data - make sure it's in the same dictionary 
aqi <- read.csv("annual_aqi_by_county_2020.csv")
data2020 <- load("2020data.rdata") # use data for the variable name
```

```{r}
# Load packages
library(dplyr)
library(stringr)
```

```{r}
data <- data %>% 
  rename(County = Name) %>%  # renames the column name
  mutate(County = str_replace(County, "(?i) county", "")) # remove the word county from each entry
```

```{r}
county_data <- data %>% 
  inner_join(aqi, by = c("County", "State")) # inner join
```

```{r}
# Rename aqi columns 
county_data <- county_data %>% 
  rename("aqi_days" = "Days.with.AQI",
        "co_days" = "Days.CO",
        "no2_days" = "Days.NO2",
        "ozone_days" = "Days.Ozone",
        "pm2.5_days" = "Days.PM2.5",
        "pm10_days" = "Days.PM10",
        "good_days" = "Good.Days",
        "moderate_days" = "Moderate.Days",
        "unhealthy_for_sensitive_groups_days" = "Unhealthy.for.Sensitive.Groups.Days",
        "unhealthy_days" = "Unhealthy.Days",
        "very_unhealthy_days" = "Very.Unhealthy.Days",
        "hazardous_days" = "Hazardous.Days",
        "max_aqi" = "Max.AQI",
        "90th_percentile_aqi"="X90th.Percentile.AQI",
        "median_aqi" = "Median.AQI")
```

