---
title: "Lexa_181_analysis"
author: "Alexandra Treml"
date: "2024-11-01"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(sf)
library(tigris)
library(plotly)
```

```{r}
#DATA LOADING AND CLEANING

#load data
load("final_data.Rdata")
df <- county_data
df <- df %>%
  mutate(FIPS = sprintf("%05d", as.numeric(FIPS)))

state <- df %>%
  group_by(State) %>%
  select(-FIPS, -County) %>%
  summarise(across(everything(), mean, na.rm = TRUE)) #group by state take take means for all numeric values for later plotly chart

#scatterplot of access to exercise and rurality
ggplot(df, aes(x = rural_2020, y = access_to_exercise_2020)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") + 
  labs(title = "Scatterplot of Access to Exercise vs. Rurality",
       x = "Rurality (rural_2020)",
       y = "Access to Exercise") +
  theme_minimal()

#scatterplot of good days aqi and rural 
ggplot(df, aes(x = rural_2020, y = good_days)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +  
  labs(title = "Scatterplot of Good Days vs. Rurality",
       x = "Rurality (rural_2020)",
       y = "Number of Good Days") +
  theme_minimal()

#scatterplot of adult obesity and rurality
ggplot(df, aes(x = rural_2020, y = adult_obesity_2020)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "green") +  
  labs(title = "Scatterplot of Adult Obesity vs. Rurality",
       x = "Rurality (rural_2020)",
       y = "Obesity %") +
  theme_minimal()

#spearman test for rurality and obesity 
spearman_obesity_rurality <- cor.test(df$adult_obesity_2020, df$rural_2020, method = "spearman")
spearman_obesity_rurality 
#results: p value is significant, so there is a moderately positive relationship between obesity and rurality
```
```{r}
df$good_days <- as.numeric(df$good_days) #make sure good_days are numeric

#scatterplot of obesity and rurality, colored by median aqi
ggplot(df, aes(x = rural_2020, y = adult_obesity_2020)) +
  geom_point(aes(color = median_aqi)) +
  labs(title = "Adult Obesity vs. Rurality with Good Air Quality",
       x = "Rurality",
       y = "Adult Obesity %") +
  scale_color_gradient(low = "red", high = "green")+
  theme_minimal()
```

```{r}
library(corrplot)
library(ggcorrplot)

#drop unnecessary variables
df_num <- df %>%
  select(-FIPS, -County, -State, -access_to_exercise_2020, -acsc_admit_rate_2020, -adult_diabetic_rate_2020,-dentist_rate_2020, -driving_mortality_2020, -chlamydia_2020, -dui_deaths_2020, -excess_drinking_2020, -fair_or_poor_health_2020, -food_env_index_2020, -food_insecure_2020, -food_insecure_2020, free_reduced_lunch_2020, -injury_death_rate_2020, -limited_healthy_food_2020, -mammogram_2020, -minor_2020, -over_65_2020, - pcp_rate_2020, -rural_2020, -severe_housing_prob_2020, -smoking_rate_2020, -social_association_rate_2020, -teen_birth_rate_2020,  -unemployment_2020, -uninsured_2020, -uninsured_v2_2020, -ypll_2020, -Year, -"90th_percentile_aqi", -co_days, -no2_days, -ozone_days, -pm2.5_days, -pm10_days, -age_adj_mortality_2020)

cor_matrix <- cor(df_num, use = "complete.obs") #set up corr matrix
print(cor_matrix)

ggcorrplot(cor_matrix, lab = TRUE, lab_size = 1, #plot corr matrix
           colors = c("red", "white", "blue"),
           title = "Correlation Matrix")
```


```{r}
#plot static counties, hazardous air quality days 
options(tigris_use_cache = TRUE)  # Caches shapefiles for faster loading
us_counties <- counties(cb = TRUE, year = 2021, class = "sf") #grab all us county data via sf

data <- df %>%
  mutate(FIPS = as.character(FIPS)) #turn FIPS back to char

us_counties <- us_counties %>%
  mutate(FIPS = as.character(GEOID))  # GEOID is the FIPS column in `us_counties`

map_data <- left_join(us_counties, data, by = "FIPS") #join county index with original data

#plot on a map, with options of which part of the US to show 
ggplot(map_data) +
  geom_sf(aes(fill = median_aqi), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("green", "yellow", "red")) +
  labs(title = "Median AQI by County") +
  coord_sf(xlim = c(-80, -66), ylim = c(38, 47), expand = FALSE) +  # Northeast bounds
  #coord_sf(xlim = c(-125, -66), ylim = c(24, 50), expand = FALSE) +  # Limits for continental U.S.
  #coord_sf(xlim = c(-105, -80), ylim = c(36, 49), expand = FALSE) + #Midwest
  #coord_sf(xlim = c(-106, -75), ylim = c(25, 39), expand = FALSE) + #South
  #coord_sf(xlim = c(-125, -102), ylim = c(31, 49), expand = FALSE) + #West
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )
```
```{r}
#dynamic county map with plotly
p <- ggplot(map_data) +
  geom_sf(aes(fill = median_aqi, text = paste("County:", County, "<br>State:", State, "<br>AQI:", median_aqi, "%")), 
          color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("green", "yellow", "red")) +
  labs(title = "Median AQI by County in 2020") +
  coord_sf(xlim = c(-125, -66), ylim = c(24, 50), expand = FALSE) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )

#show plot
ggplotly(p, tooltip = "text")
```
```{r}
#dynamic plot by state, annotated by median_aqi 
us_states <- states(cb = TRUE, year = 2021, class = "sf")
state_data <- left_join(us_states, state, by = c("NAME" = "State"))
head(state_data)

p <- ggplot(state_data) +
  geom_sf(aes(fill = median_aqi, text = paste("Median AQI:", round(median_aqi, 1))), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("green", "yellow", "red"), name = "Median AQI (%)")+
  labs(title = "Median AQI by State in 2020") +
  coord_sf(xlim = c(-125, -66), ylim = c(24, 50), expand = FALSE) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank()
  )

# Convert to interactive plot with plotly
ggplotly(p, tooltip = "text")
```

```{r}
#Using Census API data to compare population and distribution in Maricopa, AZ
library(tidycensus)

census_api_key("fa16260e4ce6c6a10484bcbe83d7b382ecce59f2", install = TRUE, overwrite = TRUE)

v1 <- load_variables(2020, "acs5", cache = TRUE)

health_vars <- v1[grep("obese", v1$label, ignore.case = TRUE), ]

az <- get_acs(geography = "county",
                             state = "AZ",
                             year = 2020,
                             variables = c(popn = "B03002_001",  # Total population
                                           white = "B03002_003", 
                                           blk = "B03002_004",
                                           hisp = "B03002_012",
                                           hlthInsCov="B27001_001",
                                           medHouseInc="B19013_001",
                                           resp_ther_n = "B24114_214"),
                             survey = "acs5",
                             output = "wide")

az_maricopa <- az %>%
  filter(GEOID == '04013') %>%
  select(-ends_with("M")) %>%
  rename_with(~ gsub("E$", "", .)) #regex from E to the end 

head(az_maricopa)
```
```{r}
#find population n in maricopa county in our data to compare
pop_n_maricopa <- df %>%
  filter(State == "Arizona") %>%
  filter(County == "Maricopa")

pop_n_maricopa

#4412779	- 4410824	

# Boxplot for Adult Obesity
ggplot(df, aes(y = adult_obesity_2020)) +
  geom_boxplot(fill = "lightblue", color = "darkblue", outlier.color = "black", outlier.shape = 16, outlier.size = 2) +
  labs(y = "Adult Obesity Rate") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 14)
  )

# Boxplot for Limited Healthy Food
ggplot(df, aes(y = limited_healthy_food_2020)) +
  geom_boxplot(fill = "lightgreen", color = "darkgreen", outlier.color = "black", outlier.shape = 16, outlier.size = 2) +
  labs(y = "% Population with Limited Healthy Food Access") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 14)
  )

# Boxplot for Life Expectancy
ggplot(df, aes(y = life_expectancy_2020)) +
  geom_boxplot(fill = "lightcoral", color = "darkred", outlier.color = "black", outlier.shape = 16, outlier.size = 2) +
  labs(y = "Life Expectancy (Years)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 14)
  )
#access to exercise
ggplot(df, aes(y = access_to_exercise_2020)) +
  geom_boxplot(fill = "purple", color = "darkblue", 
               outlier.color = "black", outlier.shape = 16, 
               outlier.size = 2) +
  labs(y = "% Population with Access to Exercise") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 14)
  )
```
```{r}
#LIFE EXPECTANCY OUTLIERS
life_exp <- df %>%
select(State, County, life_expectancy_2020, population_2020) %>%
arrange(desc(life_expectancy_2020))
```
